### ISSUE TITLE
A la hora de leer los datos de la memoria, los ultimos dos datos son basura

### ISSUE THREAD

**Issue by ivanvig** [ivanvig/2dconv-FPGA#1]
Como para una imagen de alto N, se producen N-2 resultados de convolucion, habria que cambiar la condicion del chblock en el estado de salida, para no estar sacando esos ultimos bits que quedaron en la memoria.

**Comment by ssulca** [comment]
Ahi pushe la solucion he hice un merge con la master  de la FSM con ese cambio , en el estado END of proccess solo recorre a N-2 para eviar sacar esos datos basura, lo simule y esta funcionando... hasta emojis tiene github jaja
